relativeURLs = true
title = "Anina Schwarzenbach"
theme = "academimal"
sectionPagesMenu = "main"
defaultContentLanguage = "en"

[author]
name = "Anina Schwarzenbach"

[markup] # needed to add html in .md
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
title = "Senior Researcher,"
institution = "University of Bern"
logo = "Anina_Schwarzenbach_006.jpg"
Twitter = "a_schwarzenbach"
Email = "anina.schwarzenbach@unibe.ch"